data_sets:
    - name: 5D_47B1MUT_1
      path: FASTQ/RNAseq/47B1MUT_5D/rep1/
      paired: True
      readsfile1: 5D_47B1MUT_1_TGGACTCT-CCGTAAGA_S5_L002_R1_001.fastq
      readsfile2: 5D_47B1MUT_1_TGGACTCT-CCGTAAGA_S5_L002_R2_001.fastq
      rep: 1
      day: 5
      genotype: [47b1,]
      housing: group
      subgroups: [all,2_days_difference]
      tissue: antennae
    - name: 5D_47B1MUT_2
      path: FASTQ/RNAseq/47B1MUT_5D/rep2/
      paired: True
      readsfile1: 5D_47B1MUT_2_GTCGAAGA-CAATGTGG_S6_L002_R1_001.fastq
      readsfile2: 5D_47B1MUT_2_GTCGAAGA-CAATGTGG_S6_L002_R2_001.fastq
      rep: 2
      day: 5
      genotype: [47b1,]
      housing: group
      subgroups: [all,2_days_difference]
      tissue: antennae
    - name: 5D_47B1MUT_3
      path: FASTQ/RNAseq/47B1MUT_5D/rep3/
      paired: True
      readsfile1: 5D_47B1MUT_3_GTCATCGA-AGTGGATC_S7_L002_R1_001.fastq
      readsfile2: 5D_47B1MUT_3_GTCATCGA-AGTGGATC_S7_L002_R2_001.fastq
      rep: 3
      day: 5
      genotype: [47b1,]
      housing: group
      subgroups: [all,2_days_difference]
      tissue: antennae
    - name: 5D_88A47B2MUT_1
      path: FASTQ/RNAseq/88A47B2MUT_5D/rep1/
      paired: True
      readsfile1: 5D_88A47B2MUT_1_GATGTGTG-CATGGCTA_S8_L002_R1_001.fastq
      readsfile2: 5D_88A47B2MUT_1_GATGTGTG-CATGGCTA_S8_L002_R2_001.fastq
      rep: 1
      day: 5
      genotype: [47b2,88a,]
      housing: group
      subgroups: [all,47b_on_88a]
      tissue: antennae
    - name: 5D_88A47B2MUT_2
      path: FASTQ/RNAseq/88A47B2MUT_5D/rep2/
      paired: True
      readsfile1: 5D_88A47B2MUT_2_ACGACTTG-TCGCTGTT_S9_L002_R1_001.fastq
      readsfile2: 5D_88A47B2MUT_2_ACGACTTG-TCGCTGTT_S9_L002_R2_001.fastq
      rep: 2
      day: 5
      genotype: [47b2,88a,]
      housing: group
      subgroups: [all,47b_on_88a]
      tissue: antennae
    - name: 5D_88A47B2MUT_3
      path: FASTQ/RNAseq/88A47B2MUT_5D/rep3/
      paired: True
      readsfile1: 5D_88A47B2MUT_3_TGCTTCCA-ATCGATCG_S10_L002_R1_001.fastq
      readsfile2: 5D_88A47B2MUT_3_TGCTTCCA-ATCGATCG_S10_L002_R2_001.fastq
      rep: 3
      day: 5
      genotype: [47b2,88a,]
      housing: group
      subgroups: [all,47b_on_88a]
      tissue: antennae
    - name: 5D_88AMUT_1
      path: FASTQ/RNAseq/88AMUT_5D/rep1/
      paired: True
      readsfile1: 5D_88AMUT_1_ACCACGAT-TTGCAGAC_S11_L002_R1_001.fastq
      readsfile2: 5D_88AMUT_1_ACCACGAT-TTGCAGAC_S11_L002_R2_001.fastq
      rep: 1
      day: 5
      genotype: [88a,]
      housing: group
      subgroups: [all,47b_on_88a]
      tissue: antennae
    - name: 5D_88AMUT_2
      path: FASTQ/RNAseq/88AMUT_5D/rep2/
      paired: True
      readsfile1: 5D_88AMUT_2_AGCACTTC-TTGGACGT_S12_L002_R1_001.fastq
      readsfile2: 5D_88AMUT_2_AGCACTTC-TTGGACGT_S12_L002_R2_001.fastq
      rep: 2
      day: 5
      genotype: [88a,]
      housing: group
      subgroups: [all,47b_on_88a]
      tissue: antennae
    - name: 5D_88AMUT_3
      path: FASTQ/RNAseq/88AMUT_5D/rep3/
      paired: True
      readsfile1: 5D_88AMUT_3_TTGCGAAG-AGCGTGTT_S13_L002_R1_001.fastq
      readsfile2: 5D_88AMUT_3_TTGCGAAG-AGCGTGTT_S13_L002_R2_001.fastq
      rep: 3
      day: 5
      genotype: [88a,]
      housing: group
      subgroups: [all,47b_on_88a]
      tissue: antennae
    - name: 7D_47B1MUT_1
      path: FASTQ/RNAseq/47B1MUT_7D/rep1/
      paired: True
      readsfile1: 7D_47B1MUT_1_GTTGACCT-AAGCACTG_S14_L002_R1_001.fastq
      readsfile2: 7D_47B1MUT_1_GTTGACCT-AAGCACTG_S14_L002_R2_001.fastq
      rep: 1
      day: 7
      genotype: [47b1,]
      housing: group
      subgroups: [all,grpWtVs47b,grpWtVsMut,hausWtVsMut,hausWtVsMut_noFru,2_days_difference]
      tissue: antennae
    - name: 7D_47B1MUT_2
      path: FASTQ/RNAseq/47B1MUT_7D/rep2/
      paired: True
      readsfile1: 7D_47B1MUT_2_CACCTGTT-GCTATCCT_S15_L002_R1_001.fastq
      readsfile2: 7D_47B1MUT_2_CACCTGTT-GCTATCCT_S15_L002_R2_001.fastq
      rep: 2
      day: 7
      genotype: [47b1,]
      housing: group
      subgroups: [all,grpWtVs47b,grpWtVsMut,hausWtVsMut,hausWtVsMut_noFru,2_days_difference]
      tissue: antennae
    - name: 7D_47B1MUT_3
      path: FASTQ/RNAseq/47B1MUT_7D/rep3/
      paired: True
      readsfile1: 7D_47B1MUT_3_ACTCTCGA-TGGTACAG_S16_L002_R1_001.fastq
      readsfile2: 7D_47B1MUT_3_ACTCTCGA-TGGTACAG_S16_L002_R2_001.fastq
      rep: 3
      day: 7
      genotype: [47b1,]
      housing: group
      subgroups: [all,grpWtVs47b,grpWtVsMut,hausWtVsMut,hausWtVsMut_noFru,2_days_difference]
      tissue: antennae
    - name: 7D_67DMUT_1
      path: FASTQ/RNAseq/67DMUT_7D/rep1/
      paired: True
      readsfile1: 7D_67DMUT_1_AGTTCGTC-GATCGAGT_S17_L002_R1_001.fastq
      readsfile2: 7D_67DMUT_1_AGTTCGTC-GATCGAGT_S17_L002_R2_001.fastq
      rep: 1
      day: 7
      genotype: [67d,]
      housing: group
      subgroups: [all,grpWtVs67d,grpWtVsMut,hausWtVsMut,hausWtVsMut_noFru]
      tissue: antennae
    - name: 7D_67DMUT_2
      path: FASTQ/RNAseq/67DMUT_7D/rep2/
      paired: True
      readsfile1: 7D_67DMUT_2_CGCAATCT-ATGCCTGT_S18_L002_R1_001.fastq
      readsfile2: 7D_67DMUT_2_CGCAATCT-ATGCCTGT_S18_L002_R2_001.fastq
      rep: 2
      day: 7
      genotype: [67d,]
      housing: group
      subgroups: [all,grpWtVs67d,grpWtVsMut,hausWtVsMut,hausWtVsMut_noFru]
      tissue: antennae
    - name: 7D_67DMUT_3
      path: FASTQ/RNAseq/67DMUT_7D/rep3/
      paired: True
      readsfile1: 7D_67DMUT_3_CGTGTGTA-TTCGTTGG_S19_L002_R1_001.fastq
      readsfile2: 7D_67DMUT_3_CGTGTGTA-TTCGTTGG_S19_L002_R2_001.fastq
      rep: 3
      day: 7
      genotype: [67d,]
      housing: group
      subgroups: [all,grpWtVs67d,grpWtVsMut,hausWtVsMut,hausWtVsMut_noFru]
      tissue: antennae
    - name: 7D_GROUPHOUSE_1
      path: FASTQ/RNAseq/GROUPHOUSE_7D/rep1/
      paired: True
      readsfile1: 7D_GROUPHOUSE_1_CTGATCGT-ATATGCGC_S20_L002_R1_001.fastq
      readsfile2: 7D_GROUPHOUSE_1_CTGATCGT-ATATGCGC_S20_L002_R2_001.fastq
      rep: 1
      day: 7
      genotype: [wt,]
      housing: group
      subgroups: [all,wtHousing,grpWtVs47b,grpWtVs67d,grpWtVsFru,grpWtVsMut,hausWtVsMut,hausWtVsMut_noFru,cantonWt]
      tissue: antennae
    - name: 7D_GROUPHOUSE_2
      path: FASTQ/RNAseq/GROUPHOUSE_7D/rep2/
      paired: True
      readsfile1: 7D_GROUPHOUSE_2_TACGCTAC-ATCACACG_S21_L002_R1_001.fastq
      readsfile2: 7D_GROUPHOUSE_2_TACGCTAC-ATCACACG_S21_L002_R2_001.fastq
      rep: 2
      day: 7
      genotype: [wt,]
      housing: group
      subgroups: [all,wtHousing,grpWtVs47b,grpWtVs67d,grpWtVsFru,grpWtVsMut,hausWtVsMut,hausWtVsMut_noFru,cantonWt]
      tissue: antennae
    - name: 7D_GROUPHOUSE_3
      path: FASTQ/RNAseq/GROUPHOUSE_7D/rep3/
      paired: True
      readsfile1: 7D_GROUPHOUSE_3_CCTTGATC-ACTCCATC_S22_L002_R1_001.fastq
      readsfile2: 7D_GROUPHOUSE_3_CCTTGATC-ACTCCATC_S22_L002_R2_001.fastq
      rep: 3
      day: 7
      genotype: [wt,]
      housing: group
      subgroups: [all,wtHousing,grpWtVs47b,grpWtVs67d,grpWtVsFru,grpWtVsMut,hausWtVsMut,hausWtVsMut_noFru,cantonWt]
      tissue: antennae
    - name: 7D_ISOLATED_1
      path: FASTQ/RNAseq/ISOLATED_7D/rep1/
      paired: True
      readsfile1: 7D_ISOLATED_1_TGTGACTG-GATAGGCT_S23_L002_R1_001.fastq
      readsfile2: 7D_ISOLATED_1_TGTGACTG-GATAGGCT_S23_L002_R2_001.fastq
      rep: 1
      day: 7
      genotype: [wt,]
      housing: isolated
      subgroups: [all,wtHousing,hausWtVsMut,hausWtVsMut_noFru]
      tissue: antennae
    - name: 7D_ISOLATED_2
      path: FASTQ/RNAseq/ISOLATED_7D/rep2/
      paired: True
      readsfile1: 7D_ISOLATED_2_GAGCAGTA-ACAGCTCA_S24_L002_R1_001.fastq
      readsfile2: 7D_ISOLATED_2_GAGCAGTA-ACAGCTCA_S24_L002_R2_001.fastq
      rep: 2
      day: 7
      genotype: [wt,]
      housing: isolated
      subgroups: [all,wtHousing,hausWtVsMut,hausWtVsMut_noFru]
      tissue: antennae
    - name: 7D_ISOLATED_3
      path: FASTQ/RNAseq/ISOLATED_7D/rep3/
      paired: True
      readsfile1: 7D_ISOLATED_3_TGGTAGCT-CAACACCT_S25_L002_R1_001.fastq
      readsfile2: 7D_ISOLATED_3_TGGTAGCT-CAACACCT_S25_L002_R2_001.fastq
      rep: 3
      day: 7
      genotype: [wt,]
      housing: isolated
      subgroups: [all,wtHousing,hausWtVsMut,hausWtVsMut_noFru]
      tissue: antennae
    - name: FRULEXAFRU440_1
      path: FASTQ/RNAseq/FRULEXAFRU440/rep1/
      paired: True
      readsfile1: FRULEXAFRU440_1_CTTCGACT-GCAAGATC_S26_L002_R1_001.fastq
      readsfile2: FRULEXAFRU440_1_CTTCGACT-GCAAGATC_S26_L002_R2_001.fastq
      rep: 1
      day: 7
      genotype: [FruLexaFru440,]
      housing: group
      subgroups: [all,grpWtVsFru,grpWtVsMut,hausWtVsMut]
      tissue: antennae
    - name: FRULEXAFRU440_2
      path: FASTQ/RNAseq/FRULEXAFRU440/rep2/
      paired: True
      readsfile1: FRULEXAFRU440_2_TGAGCTAG-AACCGTTC_S27_L002_R1_001.fastq
      readsfile2: FRULEXAFRU440_2_TGAGCTAG-AACCGTTC_S27_L002_R2_001.fastq
      rep: 2
      day: 7
      genotype: [FruLexaFru440,]
      housing: group
      subgroups: [all,grpWtVsFru,grpWtVsMut,hausWtVsMut]
      tissue: antennae
    - name: FRULEXAFRU440_3
      path: FASTQ/RNAseq/FRULEXAFRU440/rep3/
      paired: True
      readsfile1: FRULEXAFRU440_3_AGAGTAGC-TACGCCTT_S28_L002_R1_001.fastq
      readsfile2: FRULEXAFRU440_3_AGAGTAGC-TACGCCTT_S28_L002_R2_001.fastq
      rep: 3
      day: 7
      genotype: [FruLexaFru440,]
      housing: group
      subgroups: [all,grpWtVsFru,grpWtVsMut,hausWtVsMut]
      tissue: antennae
      SRA: a

    - name: CantonS_1
      path: FASTQ/RNAseq/CantonS/rep1/
      paired: True
      readsfile1: SRR8890850_1.fastq
      readsfile2: SRR8890850_2.fastq
      rep: 1
#      day: adult
      genotype: [CantonS,]
      housing: group
      subgroups: [all,cantonAmos,cantonWt]
      tissue: antennae
      SRA: SRR8890850
    - name: CantonS_2
      path: FASTQ/RNAseq/CantonS/rep2/
      paired: True
      readsfile1: SRR8890851_1.fastq
      readsfile2: SRR8890851_2.fastq
      rep: 2
#      day: adult
      genotype: [CantonS,]
      housing: group
      subgroups: [all,cantonAmos,cantonWt]
      tissue: antennae
      SRA: SRR8890851
    - name: CantonS_3
      path: FASTQ/RNAseq/CantonS/rep3/
      paired: True
      readsfile1: SRR8890849_1.fastq
      readsfile2: SRR8890849_2.fastq
      rep: 3
#      day: adult
      genotype: [CantonS,]
      housing: group
      subgroups: [all,cantonAmos,cantonWt]
      tissue: antennae
      SRA: SRR8890849
    - name: amos_1
      path: FASTQ/RNAseq/amos/rep1/
      paired: True
      readsfile1: SRR8884118_1.fastq
      readsfile2: SRR8884118_2.fastq
      rep: 1
#      day: adult
      genotype: [amos,]
      housing: group
      subgroups: [all,cantonAmos,]
      tissue: antennae
      SRA: SRR8884118
    - name: amos_2
      path: FASTQ/RNAseq/amos/rep2/
      paired: True
      readsfile1: SRR8890847_1.fastq
      readsfile2: SRR8890847_2.fastq
      rep: 2
#      day: adult
      genotype: [amos,]
      housing: group
      subgroups: [all,cantonAmos,]
      tissue: antennae
      SRA: SRR8890847
    - name: amos_3
      path: FASTQ/RNAseq/amos/rep3/
      paired: True
      readsfile1: SRR8890848_1.fastq
      readsfile2: SRR8890848_2.fastq
      rep: 3
#      day: adult
      genotype: [amos,]
      housing: group
      subgroups: [all,cantonAmos,]
      tissue: antennae
      SRA: SRR8890848




reference_genomes:
    - name: dm6main
      species: drosophila melanogaster
      path: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_melanogaster/dm6.main.fa
      fai: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_melanogaster/dm6.main.fa.fai
      bowtie: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_melanogaster/dm6.main_bowtie/dm6.main
      split: /proj/cdjones_lab/Genomics_Data_Commons/genomes/drosophila_melanogaster/dm6.main_split/
      source: UCSC Genome Browser

annotations:
    - name: dm6_genes
      bed_path: /proj/cdjones_lab/Genomics_Data_Commons/annotations/drosophila_melanogaster/dmel-all-r6.13.bed
      gtf_path: /proj/cdjones_lab/Genomics_Data_Commons/annotations/drosophila_melanogaster/dmel-all-r6.13.gtf
      derived: False
    - name: dm6_repeats
      bed_path: /proj/cdjones_lab/Genomics_Data_Commons/annotations/drosophila_melanogaster/dm6.repeatMasker.main.bed
      derived: False
    - name: fru_exons
      bed_path: utils/annotations/fru_ex.bed
      gtf_path: utils/annotations/fru_ex.gtf
      derived: False
    - name: fru_junct
      bed_path: utils/annotations/fru_ex.bed
      gtf_path: utils/annotations/fru_exonJunctions.gtf
      derived: False
    - name: fru_intron
      bed_path: utils/annotations/fru_ex.bed
      gtf_path: utils/annotations/fru_introns.gtf
      derived: False
    - name: ionotropic
      bed_path: utils/annotations/ionotropic.bed
      base: dm6_genes
      derived: True
    - name: nervSysDev
      bed_path: utils/annotations/nervSysDev.bed
      base: dm6_genes
      derived: True
    - name: histoneMod
      bed_path: utils/annotations/histoneMod.bed
      base: dm6_genes
      derived: True
    - name: mating
      bed_path: utils/annotations/mating.bed
      base: dm6_genes
      derived: True
    - name: synapseSig
      bed_path: utils/annotations/synapseSig.bed
      base: dm6_genes
      derived: True
    - name: brysonsList
      bed_path: utils/annotations/brysonsList.bed
      base: dm6_genes
      derived: True


gene_queries:
    - name: ionotropic
      list_path: utils/geneLists/ionotropic_FBgn.clean.txt
      base: dm6_genes
      bed_path: utils/annotations/ionotropic.bed
    - name: nervSysDev
      list_path: utils/geneLists/nervSysDev_FBgn.clean.txt
      base: dm6_genes
      bed_path: utils/annotations/nervSysDev.bed
    - name: histoneMod
      list_path: utils/geneLists/histoneMod_FBgn.clean.txt
      base: dm6_genes
      bed_path: utils/annotations/histoneMod.bed
    - name: mating
      list_path: utils/geneLists/mating_FBgn.clean.txt
      base: dm6_genes
      bed_path: utils/annotations/mating.bed
    - name: synapseSig
      list_path: utils/geneLists/synapseSig_FBgn.clean.txt
      base: dm6_genes
      bed_path: utils/annotations/synapseSig.bed
    - name: brysonsList
      list_path: utils/geneLists/bryson_FBgn.clean.txt 
      base: dm6_genes
      bed_path: utils/annotations/brysonsList.bed
    - name: brysonPriority
      list_path: utils/geneLists/brysonRush_FBgn.clean.txt 
      base: dm6_genes
      bed_path: utils/annotations/brysonPriority.bed
    - name: ionChannel
      list_path: utils/geneLists/ionChannel_FBgn.clean.txt
      base: dm6_genes
      bed_path: utils/annotations/ionChannel.bed



contrasts:
    - name: wildTypeHousing
      design: ~ housing
      filt: wtHousing
      vars: [rep, housing]
      ref: ["1", "group" ]
    - name: grpWtVs47b
      design: ~ genotype
      filt: grpWtVs47b
      vars: [rep, genotype]
      ref: ["1", "wt"]
    - name: grpWtVs67d
      design: ~ genotype
      filt: grpWtVs67d
      vars: [rep, genotype]
      ref: ["1", "wt"]
    - name: grpWtVsFru
      design: ~ genotype
      filt: grpWtVsFru
      vars: [rep, genotype]
      ref: ["1", "wt"]
    - name: grpWtVsMut
      design: ~ genotype
      filt: grpWtVsMut
      vars: [rep, genotype]
      ref: ["1", "wt"]
    - name: hausWtVsMut
      design: ~ genotype + housing
      filt: hausWtVsMut
      vars: ["rep", "genotype", "housing"]
      ref: ["1", "wt", "group" ]
    - name: hausWtVsMut_noFru
      design: ~ genotype + housing
      filt: hausWtVsMut_noFru
      vars: ["rep", "genotype", "housing"]
      ref: ["1", "wt", "group" ]
    - name: 47b_on_88a
      design: ~ genotype 
      filt: 47b_on_88a
      vars: ["rep", "genotype"]
      ref: ["1", "88a" ]
    - name: 2_days_difference
      design: ~ day 
      filt: 2_days_difference
      vars: ["rep", "day"]
      ref: ["1", "5" ]
    - name: cantonAmos
      design: ~ genotype
      filt: cantonAmos
      vars: ["rep", "genotype"]
      ref: ["1", "CantonS" ]
    - name: cantonWt
      design: ~ genotype
      filt: cantonWt
      vars: ["rep", "genotype"]
      ref: ["1", "wt" ]


